[package]
name = "lets-do-it"
version = "1.0.6"
edition = "2024"
rust-version = "1.85"

[dependencies]
rustyline = "17.0.2"
indexmap = { version = "2.12.0", features = ["serde"] }
serde_json = "1.0.145"
